### ISSUE TITLE
Prometheus with Basic Auth

### ISSUE THREAD

**Issue by benjaminguttmann-avtq** [prometheus/promlens#38]
Currently Promlens does not support if Prometheus is protected via basic auth, would be great if that could be added.

**Comment by avdicl** [comment]
+1. Would love to see either Basic Auth working with PromLens or PromLens incorporated into the Prometheus Web UI as an additional option.

**Comment by Monpoke** [comment]
Hey, same issue here!

I am hosting PromLens on Kubernetes and I used a workaround this way:
- Promlens is hosted in same namespace than Prometheus
- I declared two ingress ressources:
1. One to Promlens service
2. Another one, on same hostname, which is a proxy to prometheus service. This way, prometheus api is served on same hostname and on prefix: /prometheus

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://nginx-ldap-auth.kube-system.svc.cluster.local:5555 # our basic-auth system
  name: promlens
  namespace: monitoring
spec:
  ingressClassName: ingress-private
  rules:
  - host: promlens.myfqdn
    http:
      paths:
      - backend:
          service:
            name: promlens
            port:
              number: 8080
        path: /
        pathType: Prefix
``` 

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://nginx-ldap-auth.kube-system.svc.cluster.local:5555
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: promlens-to-prometheus
  namespace: monitoring
spec:
  ingressClassName: ingress-private
  rules:
  - host: promlens.myfqdn
    http:
      paths:
      - backend:
          service:
            name: prometheus-prometheus
            port:
              number: 9090
        path: /prometheus(/|$)(.*)
        pathType: Prefix
```

Thanks for this awesome tool! :)
